/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndianServicesRouteImport } from './routes/indian-services'
import { Route as InternationalServicesRouteImport } from './routes/international-services'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesBlogsIndexRouteImport } from './routes/resources/blogs/index'
import { Route as ResourcesBlogsSlugRouteImport } from './routes/resources/blogs/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndianServicesRoute = IndianServicesRouteImport.update({
  id: '/indian-services',
  path: '/indian-services',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalServicesRoute = InternationalServicesRouteImport.update({
  id: '/international-services',
  path: '/international-services',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesBlogsIndexRoute = ResourcesBlogsIndexRouteImport.update({
  id: '/resources/blogs/',
  path: '/resources/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesBlogsSlugRoute = ResourcesBlogsSlugRouteImport.update({
  id: '/resources/blogs/$slug',
  path: '/resources/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/indian-services': typeof IndianServicesRoute
  '/international-services': typeof InternationalServicesRoute
  '/marketing': typeof MarketingRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/': typeof AdminIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/resources/blogs/$slug': typeof ResourcesBlogsSlugRoute
  '/resources/blogs/': typeof ResourcesBlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/indian-services': typeof IndianServicesRoute
  '/international-services': typeof InternationalServicesRoute
  '/marketing': typeof MarketingRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin': typeof AdminIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/resources/blogs/$slug': typeof ResourcesBlogsSlugRoute
  '/resources/blogs': typeof ResourcesBlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/indian-services': typeof IndianServicesRoute
  '/international-services': typeof InternationalServicesRoute
  '/marketing': typeof MarketingRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/': typeof AdminIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/resources/blogs/$slug': typeof ResourcesBlogsSlugRoute
  '/resources/blogs/': typeof ResourcesBlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/indian-services'
    | '/international-services'
    | '/marketing'
    | '/testimonials'
    | '/admin/'
    | '/resources/'
    | '/resources/blogs/$slug'
    | '/resources/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/indian-services'
    | '/international-services'
    | '/marketing'
    | '/testimonials'
    | '/admin'
    | '/resources'
    | '/resources/blogs/$slug'
    | '/resources/blogs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/indian-services'
    | '/international-services'
    | '/marketing'
    | '/testimonials'
    | '/admin/'
    | '/resources/'
    | '/resources/blogs/$slug'
    | '/resources/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  IndianServicesRoute: typeof IndianServicesRoute
  InternationalServicesRoute: typeof InternationalServicesRoute
  MarketingRoute: typeof MarketingRoute
  TestimonialsRoute: typeof TestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ResourcesBlogsSlugRoute: typeof ResourcesBlogsSlugRoute
  ResourcesBlogsIndexRoute: typeof ResourcesBlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indian-services': {
      id: '/indian-services'
      path: '/indian-services'
      fullPath: '/indian-services'
      preLoaderRoute: typeof IndianServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international-services': {
      id: '/international-services'
      path: '/international-services'
      fullPath: '/international-services'
      preLoaderRoute: typeof InternationalServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/blogs/': {
      id: '/resources/blogs/'
      path: '/resources/blogs'
      fullPath: '/resources/blogs/'
      preLoaderRoute: typeof ResourcesBlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/blogs/$slug': {
      id: '/resources/blogs/$slug'
      path: '/resources/blogs/$slug'
      fullPath: '/resources/blogs/$slug'
      preLoaderRoute: typeof ResourcesBlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  IndianServicesRoute: IndianServicesRoute,
  InternationalServicesRoute: InternationalServicesRoute,
  MarketingRoute: MarketingRoute,
  TestimonialsRoute: TestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ResourcesBlogsSlugRoute: ResourcesBlogsSlugRoute,
  ResourcesBlogsIndexRoute: ResourcesBlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
